basePath: /
definitions:
  models.Product:
    properties:
      category:
        type: string
      description:
        type: string
      id:
        type: string
      price:
        type: integer
      rating:
        items:
          type: integer
        type: array
      stock:
        type: integer
      title:
        type: string
    type: object
host: localhost:8082
info:
  contact: {}
  description: Tag service API in Go using Gin framework
  title: Tag Service API
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - application/json
      description: Get all products
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Product'
            type: array
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Create a new product in MongoDB
      parameters:
      - description: Product Data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create product
      tags:
      - products
  /products/{user_id}:
    delete:
      consumes:
      - application/json
      description: Delete a product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a product
      tags:
      - products
    get:
      consumes:
      - application/json
      description: Retrieve a product by user_id from the database
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Product'
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a product
      tags:
      - products
    patch:
      consumes:
      - application/json
      description: Update a product
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a product
      tags:
      - products
swagger: "2.0"
