version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./src:/app
    networks:
      - backend-network

  postgres:
    image: postgres:latest
    container_name: postgres-users
    environment:
      POSTGRES_USER: jaider
      POSTGRES_PASSWORD: 1005716614
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:alpine
    container_name: cache-users
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: redispass
    networks:
      - backend-network

volumes:
  pgdata:


networks:
  backend-network:
    driver: bridge
